# Generated by Django 3.1.2 on 2020-11-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTPConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('config', models.FileField(null=True, upload_to='Dashboard/static/config_files/RTP')),
            ],
        ),
        migrations.CreateModel(
            name='SBCConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('config', models.FileField(null=True, upload_to='Dashboard/static/config_files/SBC')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('Type', models.CharField(choices=[('ssw', 'SSW'), ('sbc', 'SBC'), ('rtp', 'RTP')], default='ssw', max_length=20)),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='SSW_SIPProfile',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SSW',
            fields=[
                ('ssw_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('SipProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.ssw_sipprofile')),
                ('server_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.server')),
            ],
        ),
        migrations.CreateModel(
            name='SBC',
            fields=[
                ('sbc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('server_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.server')),
            ],
        ),
        migrations.CreateModel(
            name='RTP',
            fields=[
                ('rtp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('server_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.server')),
            ],
        ),
    ]
