# Generated by Django 3.1.2 on 2020-10-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='SoftSwitch',
            fields=[
                ('soft_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('service_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.service')),
            ],
        ),
    ]
