# Generated by Django 3.1.2 on 2020-10-24 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('Type', models.CharField(choices=[('ssw', 'SSW'), ('sbc', 'SBC')], default='ssw', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SSWConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('config', models.FileField(null=True, upload_to='Dashboard/static/config_files/SSW')),
            ],
        ),
        migrations.CreateModel(
            name='SSW',
            fields=[
                ('ssw_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.sswconfig')),
                ('server_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.server')),
            ],
        ),
    ]
