# Generated by Django 3.1.2 on 2020-10-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBCs',
            fields=[
                ('sbc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('service_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.service')),
            ],
        ),
    ]
