# Generated by Django 3.1.2 on 2020-11-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssw',
            name='ssw_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
