# Generated by Django 3.1.2 on 2020-10-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBCConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('config', models.FileField(null=True, upload_to='Dashboard/static/config_files/SBC')),
            ],
        ),
        migrations.CreateModel(
            name='SBC',
            fields=[
                ('sbc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.sbcconfig')),
                ('server_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.server')),
            ],
        ),
    ]
