# Generated by Django 3.1.2 on 2020-11-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20201107_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssw',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.server'),
        ),
        migrations.AlterField(
            model_name='ssw',
            name='ssw_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
