# Generated by Django 3.1.2 on 2020-10-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_sbcs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SBCs',
            new_name='SBC',
        ),
    ]
