# Generated by Django 3.1.2 on 2020-10-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_sbc_sbcconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbc',
            name='config',
        ),
        migrations.RemoveField(
            model_name='ssw',
            name='config',
        ),
    ]
