# Generated by Django 3.1.2 on 2020-10-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20201026_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
