# Generated by Django 3.1.2 on 2020-11-07 13:54

import Dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20201107_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssw_sipprofile',
            name='attrs',
            field=models.JSONField(default=Dashboard.models.my_default),
        ),
    ]
