# Generated by Django 3.1.2 on 2020-10-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20201026_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-ip']},
        ),
    ]
