# Generated by Django 3.1.2 on 2020-11-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_ssw_sipprofile_attrs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssw_sipprofile',
            old_name='attrs',
            new_name='Params',
        ),
        migrations.RenameField(
            model_name='ssw_sipprofile',
            old_name='name',
            new_name='Profile_Name',
        ),
    ]
