# Generated by Django 3.1.2 on 2020-10-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20201026_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={},
        ),
    ]
