# Generated by Django 3.1.2 on 2020-10-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20201026_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['ip']},
        ),
    ]
