# Generated by Django 3.1.2 on 2020-10-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20201026_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTPConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('config', models.FileField(null=True, upload_to='Dashboard/static/config_files/RTP')),
            ],
        ),
        migrations.CreateModel(
            name='RTP',
            fields=[
                ('rtp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('server_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.server')),
            ],
        ),
    ]
