# Generated by Django 3.1.2 on 2020-10-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_rtp_rtpconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='Type',
            field=models.CharField(choices=[('ssw', 'SSW'), ('sbc', 'SBC'), ('rtp', 'RTP')], default='ssw', max_length=20),
        ),
    ]
